### ISSUE TITLE
`class` attribute of `<time>` not working

### ISSUE THREAD

**Issue by Lai-YT** [Lai-YT/web-projects#2]
```html
<time class="sender-column" datetime="2016-01-20">20 January 2016</time>
```
doesn't align right with the following CSS:
```css
.sender-column {
  text-align: right;
}
```
I have to wrap it with another `p` tag to make it work.
```html
<p class="sender-column">
  <time datetime="2016-01-20">20 January 2016</time>
</p>
```
See also: #1
